version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "bun"
    labels:
      - "dependencies"
    groups:
      all-deps:
        patterns:
          - "*"
